language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer install

stages:
  - lint
  - unit test

jobs:
  include:
    - stage: lint
      script: composer lint
    - stage: unit test
      script: php bin/phpspec run