language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install

jobs:
  include:
    - stage: lint
      script: composer lint
    - stage: test
      script: composer test