language: php
php:
  - 7.1

before_script:
  - composer install
  - composer require indigophp/doctrine-annotation-autoload

stages:
  - lint
  - unit test

jobs:
  include:
    - script: composer test
    - stage: lint
      script: composer lint